# This Makefile is set up for CS201 A1
# NOTE: All indented lines are indented with a tab character.
#       This is required.

CC=gcc
# compile for 32-bit rather than 64-bit
CFLAGS=-m32 -O0
DFLAGS=-g
PROGS=typing_word_game

all: $(PROGS)

%: %.c
	$(CC) $(CFLAGS) $(DFLAGS) $< -o $@

clean:
	rm -f $(PROGS) *.o ~* 

